spring:
  config:
    activate:
      on-profile: dev-batch
  batch:
    jdbc:
      initialize-schema: always      # Spring Batch 관련 테이블 자동 생성 설정
      isolation-level-for-create: read_committed    # Job 동시 실행 시 발생 가능한 오류 대응
    job:
      enabled: false   # 서버 실행 시 Job 자동 실행 여부
#      name: jobName