spring:
  config:
    activate:
      on-profile: dev-oauth
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - profile
              - email