spring:
  config:
    activate:
      on-profile: prod-redis
  data:
    redis:
      repositories:
        enabled: false
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
      port: ${REDIS_PORT}
      host: ${PROD_REDIS_HOST}
      password: ${REDIS_PASSWORD}