spring:
  config:
    activate:
      on-profile: prod-oauth
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "https://i12c203.p.ssafy.io:443/api/login/oauth2/code/github"
            scope:
              - profile
              - email